import './globals.css'
import Image from 'next/image'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <div className ="topnav">
              <a href="">Home</a>
              <a href="#buy">Buy</a>
              <a href="#rent">Rent</a>
              <a href="#sell">Sell</a>
              <a href="#about">About</a>
              <a href="#signIn">Sign in</a>   
              <Image 
              src="/vercel.png"
              alt="Vercel Logo"
              width={50}
              height={50}
              priority/>   
            </div>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
